# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: main

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn test
      env:
        CI: true
    - run: yarn build
      env:
        REACT_APP_PEER_HOST: ${{secrets.REACT_APP_PEER_HOST}}
        REACT_APP_PEER_PORT: 443
        REACT_APP_PEER_PATH: /
        REACT_APP_PEER_SECURE: true
        REACT_APP_PEER_CONFIG: >-
          ${{secrets.REACT_APP_PEER_CONFIG}}
        CI: true
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
      env:
        CI: true
